### PR TITLE
Explicitly state which registers are preserved across calls

### PR DESCRIPTION
**Pull request by aswaterman**

### CODE REVIEW

**Comment by asb** [comment]
Are you leaving out gp and tp because you consider them unallocatable?

**Comment by aswaterman** [comment]
Yeah, describing them as preserved across calls isn't sufficient.  Signal handlers rely on them, so they shouldn't be modified at all.

Can you think of a pithy way to express that in this table?

**Comment by asb** [comment]
Maybe just `-- (Unallocatable)` or `-- (Reserved)`. Then a comment below saying something like "In the standard ABI, the tp and gp registers should not be considered eligible for spilling - signal handlers may rely upon their value.`

**Comment by aswaterman** [comment]
Thanks - addressed.

**Pull request merged**
