### PR TITLE
Nonstandard relocs

### LINKED ISSUE #64: Customized relocation type
In our current CPU design, we extend RISC-V ISA by adding several instructions, such as GP-implied load/store. To handle these instructions, we also extend relocation type. However, there does not have any rule or guideline to add customized relocation type currently. To avid conflict, in our current design, the new relocation id is assigned from 255 and in decreasing order. Could anyone have any idea or propose to deal with this issue?

### PR DESCRIPTION
**Pull request by aswaterman**
Resolves #64

### CODE REVIEW

**Comment by asb** [comment]
Is the intention that the 192-255 space is a free-for-all, or that non-standard relocation numbers will be managed in some way? Or is this patch purposely avoiding making such a determination?

**Comment by aswaterman** [comment]
My plan was the former: chaos, just like the ISA opcode space for nonstandard extensions.  I guess I should add a sentence to that effect?

**Comment by asb** [comment]
Yes, chaos was my assumption but just leaving it marked as "reserved" without further explanation might lead someone to think there's something more managed going on. An extra sentence would be a good idea I think.

**Comment by aswaterman** [comment]
Yep.

**Pull request merged**
